# Generated by Django 4.1.5 on 2023-02-08 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File_description',
            fields=[
                ('file_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('file_format', models.CharField(max_length=50)),
                ('file_data', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('contig', models.CharField(max_length=255)),
                ('phasing', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Sample_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id1', models.CharField(max_length=50)),
                ('format_gt', models.CharField(max_length=5)),
                ('format_gq', models.CharField(max_length=5)),
                ('all_other', models.CharField(max_length=100)),
                ('File_description', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sequences.file_description')),
            ],
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id1', models.CharField(max_length=50)),
                ('chrom', models.CharField(max_length=4)),
                ('pos', models.IntegerField()),
                ('id1', models.CharField(max_length=30)),
                ('ref', models.CharField(max_length=200)),
                ('alt', models.CharField(max_length=200)),
                ('qual', models.CharField(max_length=100)),
                ('filter', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=255)),
                ('File_description', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sequences.file_description')),
            ],
        ),
    ]
