# Generated by Django 4.1.5 on 2023-02-24 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id1', models.CharField(max_length=50)),
                ('chrom', models.CharField(max_length=4)),
                ('pos', models.IntegerField()),
                ('id1', models.CharField(max_length=30)),
                ('ref', models.CharField(max_length=200)),
                ('alt', models.CharField(max_length=200)),
                ('qual', models.CharField(max_length=100)),
                ('filter', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='file_description',
            fields=[
                ('file_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('file_format', models.CharField(max_length=50)),
                ('file_data', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('contig', models.CharField(max_length=255)),
                ('phasing', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('person_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='sample_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id1', models.CharField(max_length=50)),
                ('format_gt', models.CharField(max_length=5)),
                ('format_gq', models.CharField(max_length=5)),
                ('all_other', models.CharField(max_length=100)),
                ('body_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='sequences.body')),
            ],
        ),
        migrations.CreateModel(
            name='phenotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phenotype_description', models.CharField(default=None, max_length=255)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sequences.patient')),
            ],
        ),
        migrations.AddField(
            model_name='body',
            name='file_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sequences.file_description'),
        ),
    ]
