# Generated by Django 4.1.5 on 2023-02-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(default=None, max_length=50)),
                ('chrom', models.CharField(max_length=4)),
                ('pos', models.IntegerField()),
                ('id1', models.CharField(max_length=30)),
                ('ref', models.CharField(max_length=20)),
                ('alt', models.CharField(max_length=20)),
                ('qual', models.CharField(max_length=100)),
                ('filter', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='File_description',
            fields=[
                ('file_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('file_format', models.CharField(max_length=50)),
                ('file_data', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('contig', models.CharField(max_length=255)),
                ('phasing', models.CharField(max_length=40)),
            ],
        ),
    ]
