# Generated by Django 4.1.5 on 2023-02-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='filter',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='format',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=3)),
                ('type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=3)),
                ('type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
