# Generated by Django 4.1.5 on 2023-02-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Body',
            new_name='sequence_Body',
        ),
    ]
