# Generated by Django 4.1.5 on 2023-02-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0002_rename_body_sequence_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sequence_Body',
            new_name='Body',
        ),
    ]
