# Generated by Django 4.1.5 on 2023-02-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0002_filter_format_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='filter',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='format',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='format',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='info',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='info',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
