# Generated by Django 4.1.5 on 2023-02-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0002_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
