# Generated by Django 4.1.5 on 2023-02-10 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0003_alter_patient_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='body',
            old_name='File_description',
            new_name='file_description',
        ),
        migrations.RenameField(
            model_name='sample_info',
            old_name='File_description',
            new_name='file_description',
        ),
    ]
