# Generated by Django 4.1.5 on 2023-02-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0003_alter_filter_description_alter_filter_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample_info',
            name='person_id',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
