# Generated by Django 4.1.5 on 2023-02-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0004_sample_info_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_description',
            name='file_data',
            field=models.CharField(max_length=200),
        ),
    ]
