# Generated by Django 4.1.5 on 2023-02-07 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0005_alter_body_alt_alter_body_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_description',
            fields=[
                ('file_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('file_format', models.CharField(max_length=50)),
                ('file_data', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('contig', models.CharField(max_length=255)),
                ('phasing', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='body',
            name='file_id',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='body',
            name='File_description',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='sequences.file_description'),
        ),
    ]
