# Generated by Django 4.1.5 on 2023-02-07 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0008_rename_file_id_body_file_id1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='File_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sequences.file_description'),
        ),
    ]
