# Generated by Django 4.1.5 on 2023-02-07 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0009_alter_body_file_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id1', models.CharField(max_length=50)),
                ('format_gt', models.CharField(max_length=5)),
                ('format_gq', models.CharField(max_length=5)),
                ('all_other', models.CharField(max_length=100)),
                ('File_description', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sequences.file_description')),
            ],
        ),
    ]
